name = "JuliaSyntaxFormatter"
uuid = "f8905de0-c3c2-461e-ad98-10cfc5e6268b"
authors = ["Claire Foster <aka.c42f@gmail.com> and contributors"]
version = "1.0.0-DEV"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
